### ISSUE TITLE
登录超时的处理

### ISSUE THREAD

**Issue by eyestone** [eyestone/laifu-pub#18]
登录超时后，需要App重新自动登录

**Comment by pencilSharp** [comment]
不明白什么情况，是不是登录超时后需要跳转到登录界面？

**Comment by eyestone** [comment]
不是，有个login_by_code的接口，如果登录超时，需要帮用户重新登陆

**Comment by pencilSharp** [comment]
什么情况下会出现登录超时？

**Comment by eyestone** [comment]
用户手动登录，或者自动登录都有一定的超时时间。超时后需要重新登陆
