### ISSUE TITLE
活动详情某些部字体不协调，大小不规范

### ISSUE THREAD

**Issue by eyestone** [eyestone/laifu-pub#5]
活动详情某些部字体不协调，大小不规范
某些部分看起来正常，某些部分过于太小
不统一
![2015 5 7_172948](https://cloud.githubusercontent.com/assets/8198825/7512331/d6454cb0-f4de-11e4-9c17-558182e9bf96.png)

**Comment by pencilSharp** [comment]
活动详情 ，联系主办方字体改小了

**Comment by eyestone** [comment]
不得行哈
参看android上的字体比例
弄清楚界面的整体结构
